name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js and its dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
          cache: 'yarn'
      - run: yarn install --immutable-cache
      - name: Build app
        run: yarn rw build
      - name: Run tests
        run: yarn rw test
